# Dependencies
markdown:         kramdown
highlighter:      rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
plugins: [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            A blog thing
tagline:          IT (mis)adventures
url:              https://blog.pkowalski.net
paginate:         10
baseurl:          ""
author:
  name:           Piotr Kowalski
  url:            https://blog.pkowalski.net

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/KowalskiPiotr98/KowalskiPiotr98.github.io

nav:
  - title: Discuss
    url: https://github.com/KowalskiPiotr98/KowalskiPiotr98.github.io/discussions
  - title: Software
    url: /software
  - title: Archive
    url: /archive
  - title: About
    url: /about
